CREATE DATABASE `plsql`;
USE `plsql`;
CREATE TABLE IF NOT EXISTS `DEPART` (
  `DEPART_ID` int(4) NOT NULL,
  `DEPART_NAME` varchar(30) NOT NULL,
  `MANAGER_ID` int(6)  NOT NULL,
  UNIQUE (MANAGER_ID),
  PRIMARY KEY (`DEPART_ID`)
) ;

USE `plsql`;
CREATE TABLE IF NOT EXISTS `EMPLOYEES` (
  `EMP_ID` int(4),
  `EMP_NAME` varchar(20),
  `EMAIL` char(25),
  `PHONE_NUMBER` varchar(10),
  `DEPT_ID` int(4),
  PRIMARY KEY (`EMP_ID`)
) ;

USE `plsql`;
ALTER TABLE `EMPLOYEES`
ADD `SALARY` float(8,2);

USE `plsql`;
ALTER TABLE `EMPLOYEES`
ADD CONSTRAINT DEPT_ID FOREIGN KEY (DEPT_ID) REFERENCES DEPART(DEPART_ID);

USE `plsql`;
ALTER TABLE `EMPLOYEES`
DROP CONSTRAINT DEPT_ID;

USE `plsql`;
ALTER TABLE `EMPLOYEES`
DROP `EMAIL`;

USE `plsql`;
ALTER TABLE `EMPLOYEES` RENAME `EMP1`;

USE `plsql`;
CREATE TABLE `DEPART1` LIKE `DEPART`;

USE `plsql`;
DROP TABLE `DEPART1`;